swagger: '2.0'
info:
  title: MCP Pizza
  description: MCP Pizza API Specification
  version: 1.0.0
host: ctdemo-fveqcubkfjd5bgez.westus2-01.azurewebsites.net
basePath: /
schemes:
  - https
paths:
  /mcp:
    post:
      summary: Pizza Server
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      responses:
        '200':
          description: Success